implemented fetching user info with test of the feature
devcomanda/easymeetup pull request #54
Opened 2019-02-12 10:34 UTC by berezkin88

понятия не имею, что здесь надо писать...

2019-02-12 11:17 UTC, adaleorion requested changes
Посмотри тред, который ниже я скинул,
попробуй добавить несколько юнит тестов для сервиса, 
попробуй добавить интеграционный для контроллера,

 если будут вопросы обращайся

2019-02-12 11:17 UTC, danilkuznetsov commented on src/main/java/com/devcomanda/easymeetup/service/UserServiceImpl.java
> +        return userRepository.getOne(id);
Посмотри пожалуйста этот тред https://stackoverflow.com/questions/24482117/when-use-getone-and-findone-methods-spring-data-jpa

2019-02-12 11:21 UTC, danilkuznetsov commented
есть небольшая дока про процесс https://github.com/devcomanda/easymeetup/blob/develop/docs/git.md
Уже основа есть, но возможно не много изменится.  
Если будут вопросы обращйся.

2019-02-17 09:30 UTC, berezkin88 commented
изменил ЮзерСервис, сделал тесты для него и есть интеграционный тест для ЮзерКонтроллера, который пока не работает

2019-02-18 18:47 UTC, mnjl1 commented on src/test/java/com/devcomanda/easymeetup/controller/UserControllerTest.java
> +@WithMockUser
Я не уверен, но надо ли здесь МокЮзер, если secure=false ?

2019-02-18 19:04 UTC, berezkin88 commented on src/test/java/com/devcomanda/easymeetup/controller/UserControllerTest.java
> +@WithMockUser
сейчас проверю

2019-02-18 19:09 UTC, berezkin88 commented on src/test/java/com/devcomanda/easymeetup/controller/UserControllerTest.java
> +@WithMockUser
работает и без МокЮзера, с secure = true вообще не работает

2019-02-19 21:51 UTC, mnjl1 submitted a review, later dismissed

2019-02-21 09:32 UTC, adaleorion requested changes
нужно разобраться с gitignore

2019-02-21 09:32 UTC, danilkuznetsov commented on .gitignore
> +/src/test/java/com/devcomanda/easymeetup/controller/UserControllerIntTest.java
Подскажи зачем такая конфигурация ?

2019-02-21 17:31 UTC, berezkin88 commented on .gitignore
> +/src/test/java/com/devcomanda/easymeetup/controller/UserControllerIntTest.java
пока тест не работает я его не заливаю
не подходит?

2019-02-21 17:31 UTC, berezkin88 commented on .gitignore
> +/src/test/java/com/devcomanda/easymeetup/controller/UserControllerIntTest.java
@danilkuznetsov

2019-02-21 17:49 UTC, danilkuznetsov commented on .gitignore
> +/src/test/java/com/devcomanda/easymeetup/controller/UserControllerIntTest.java
Это не проблема, проблема в том что gitignore, не лучшее место для этого, его можно добавить но заигнорить с помощью аннотации @ignore, а так это не ожиданное место

2019-02-21 17:58 UTC, berezkin88 commented on .gitignore
> +/src/test/java/com/devcomanda/easymeetup/controller/UserControllerIntTest.java
переделал

2019-02-22 16:31 UTC, FedosovMax approved these changes

2019-02-23 06:12 UTC, adaleorion approved these changes

2019-02-23 06:12 UTC, merged