37 register new user with email and password
devcomanda/easymeetup pull request #60
Opened 2019-02-16 09:43 UTC by mnjl1

connect #37

2019-02-18 20:59 UTC, berezkin88 submitted a review, later dismissed

2019-02-18 20:59 UTC, berezkin88 commented on src/main/java/com/devcomanda/easymeetup/service/UserServiceImpl.java
> +        if (userReq.getPassword() == null || userReq.getPassword().isEmpty()){
Не совсем понял этот момент - если пользователь не указал пароль, то он генерируется автоматически?
А как тогда юзер залогинется при следующем заходе?

2019-02-19 21:26 UTC, mnjl1 commented on src/main/java/com/devcomanda/easymeetup/service/UserServiceImpl.java
> +        if (userReq.getPassword() == null || userReq.getPassword().isEmpty()){
я так понял, что в этом случае сгенерится пароль и при следующем заходе этот if не сработает

2019-02-21 09:45 UTC, adaleorion requested changes
добавь темплейт для письма с активацией пожайлуста

2019-02-21 09:45 UTC, danilkuznetsov commented on src/main/java/com/devcomanda/easymeetup/service/UserServiceImpl.java
> +        if (userReq.getPassword() == null || userReq.getPassword().isEmpty()){
Кейс с паролем интересный, у нас в будущем будет несколько возможных путей для регистрации пользователя, не которые из них будут регистрироваться с помощью сторонних сервисов и будут входить без пароля. Пускай пока будет, этот метод в будущем будет изменяться и трансформироваться

2019-02-21 09:45 UTC, danilkuznetsov commented on src/main/java/com/devcomanda/easymeetup/service/MailService.java
> +                , "mails/activationEmail", context);
Я в ресурсах я не нашел thymeleaf темплейта для этого кейса, добавь его пожалуйста

2019-02-23 09:46 UTC, mnjl1 commented on src/main/java/com/devcomanda/easymeetup/service/MailService.java
> +                , "mails/activationEmail", context);
Добавил ресурс и для него сервис и метод в контроллере. Но для отображения статуса активации требуется еще два ресурса, может это часть front-end? ))

2019-02-23 17:52 UTC, danilkuznetsov commented on src/main/java/com/devcomanda/easymeetup/service/MailService.java
> +                , "mails/activationEmail", context);
Какие два ресура ? в регистрации пользователей, речь о активации не идет, для этого есть другая задача #39

2019-02-23 17:55 UTC, merged