55-filter-meetups-list-by-status
devcomanda/easymeetup pull request #63
Opened 2019-02-23 18:59 UTC by FedosovMax

connect to #55

2019-02-23 20:44 UTC, mnjl1 commented on src/main/java/com/devcomanda/easymeetup/controller/MeetupController.java
> +    @InitBinder //for converting String to Enum in getAllMeetups method
Предлагаю в пакете config создать класс webconfig и перенести туда регистрацию конвертера, как этого, так и дальнейших.

2019-02-23 20:47 UTC, FedosovMax commented on src/main/java/com/devcomanda/easymeetup/controller/MeetupController.java
> +    @InitBinder //for converting String to Enum in getAllMeetups method
Я не против, тоже считаю что отдельный каталог для этого конвертера является излишним. Если никто не будет против этого предложения, я сделаю.

2019-02-23 20:56 UTC, mnjl1 commented on src/main/java/com/devcomanda/easymeetup/controller/MeetupController.java
> +    @InitBinder //for converting String to Enum in getAllMeetups method
конвертер оставляет в своем пакете, а регистрацию его в конфиге, просто я такое раньше уже видел ))

2019-02-23 21:06 UTC, mnjl1 commented on src/main/java/com/devcomanda/easymeetup/controller/MeetupController.java
> +    public ResponseEntity<List<Meetup>> getAllMeetups(@RequestParam(name = "status", required = false) Status status) {
Вопрос: точно нужно было рефактрить метод? Если я правильно понимаю, мы теперь получаем список только по определенному статусу, а все митапы не сможем со всеми статусами. Честно говоря сам не уверен как правильно...)

2019-02-23 21:14 UTC, FedosovMax commented on src/main/java/com/devcomanda/easymeetup/controller/MeetupController.java
> +    @InitBinder //for converting String to Enum in getAllMeetups method
Это который @InitBinder аннотацией помечен в контроллере нужно перенести в конфиг, я правильно понимаю? Ну вроде правильно, не увидел сначала под какой строчкой комментарий находится.

2019-02-23 21:20 UTC, FedosovMax commented on src/main/java/com/devcomanda/easymeetup/controller/MeetupController.java
> +    public ResponseEntity<List<Meetup>> getAllMeetups(@RequestParam(name = "status", required = false) Status status) {
Я думаю, что некоторые моменты в пулл реквесте можно просто спрашивать типа "почему так" ) В данном случае, для того чтобы получать статус через запрос API GET /api/meetups?status=<some status> нужно сделать @RequestParam, но там стоит required = false, что значит, что он не обязателен. И дальше в методе указано, что если параметр tatus == null то мы просто возвращаем все записи. Но если параметр не пустой, то мы вызываем все митапы, проходимся по ним, сравнивая статус каждого из них с запрошенным статусом, и добавляем результат в лист отредактированных по статусу митапов. В общем он работает соответственно заданию : https://github.com/devcomanda/easymeetup/issues/55 , если я правильно его понял.

2019-02-23 22:25 UTC, mnjl1 commented on src/main/java/com/devcomanda/easymeetup/controller/MeetupController.java
> +    public ResponseEntity<List<Meetup>> getAllMeetups(@RequestParam(name = "status", required = false) Status status) {
Понял, спасибо)

2019-02-23 22:43 UTC, mnjl1 commented on src/main/java/com/devcomanda/easymeetup/controller/MeetupController.java
> +    @InitBinder //for converting String to Enum in getAllMeetups method
оставляй как есть, я смотрю во многих примерах как раз регистрация в контроллере, меня не много сбило с толку StatusConverter, хотя ближе по смыслу StatusEditor, и да, регистрируется в контроллере.

2019-02-23 22:43 UTC, mnjl1 submitted a review, later dismissed

2019-02-25 20:41 UTC, adaleorion requested changes

2019-02-25 20:41 UTC, danilkuznetsov commented on src/main/java/com/devcomanda/easymeetup/controller/MeetupController.java
> +            List<Meetup> meetupsByStatus = meetups.stream()
Подумай над тем как перенести эту логику в сервис, проблема в том что если мне где нибудь внутри приложения необходимо будет найти список митапов по статусу, мы будем вынуждены продублировать этот код, В конечном итоге мы получим дублирование и если в дальнейшнем мы будем что менять в логике поиска, нам прийдется менять это в двух местах

2019-02-25 20:41 UTC, danilkuznetsov commented on src/main/java/com/devcomanda/easymeetup/model/entity/Meetup.java
> +    private Status status;
Подумай над тем как замапить enum в строковое значение, для хранения в базе
цифры не информативны и их сложно различать на взгляд между собой.

2019-02-26 09:43 UTC, berezkin88 submitted a review, later dismissed

2019-03-09 16:46 UTC, mnjl1 submitted a review, later dismissed

2019-03-09 17:03 UTC, adaleorion submitted a review, later dismissed

2019-03-10 10:05 UTC, berezkin88 submitted a review, later dismissed

2019-03-23 20:18 UTC, berezkin88 approved these changes

2019-03-24 10:47 UTC, mnjl1 approved these changes

2019-03-24 20:46 UTC, merged